"""add fcm_token to users

Revision ID: 47d78292e206
Revises: a4352baf8d4b
Create Date: 2026-04-25 07:42:14.613434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47d78292e206'
down_revision: Union[str, Sequence[str], None] = 'a4352baf8d4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_face_embeddings_user_id'), 'face_embeddings', ['user_id'], unique=False)
    op.add_column('users', sa.Column('fcm_token', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'fcm_token')
    op.drop_index(op.f('ix_face_embeddings_user_id'), table_name='face_embeddings')
    # ### end Alembic commands ###
