"""create presensi table

Revision ID: a4352baf8d4b
Revises: bf3d9cb419d5
Create Date: 2026-04-24 18:02:17.142616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4352baf8d4b'
down_revision: Union[str, Sequence[str], None] = 'bf3d9cb419d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('presensi',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mahasiswa_id', sa.UUID(), nullable=False),
    sa.Column('sesi_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('hadir', 'terlambat', 'absen', 'izin', 'sakit', name='presensistatus'), nullable=False),
    sa.Column('waktu_presensi', sa.DateTime(timezone=True), nullable=True),
    sa.Column('akurasi_wajah', sa.Float(), nullable=True),
    sa.Column('mode_kelas', sa.Enum('offline', 'online', name='modekelas'), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('catatan', sa.Text(), nullable=True),
    sa.Column('diubah_oleh', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['diubah_oleh'], ['users.id'], ),
    sa.ForeignKeyConstraint(['mahasiswa_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sesi_id'], ['sesi_presensi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('presensi')
    # ### end Alembic commands ###
