"""create matakuliah, sesi_presensi, kode_usage tables

Revision ID: bf3d9cb419d5
Revises: b7658314f889
Create Date: 2026-04-24 17:44:32.568713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf3d9cb419d5'
down_revision: Union[str, Sequence[str], None] = 'b7658314f889'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matakuliah',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kode', sa.String(length=20), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('sks', sa.Integer(), nullable=False),
    sa.Column('koordinat_lat', sa.Float(), nullable=True),
    sa.Column('koordinat_lng', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kode')
    )
    op.create_table('sesi_presensi',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('matakuliah_id', sa.UUID(), nullable=False),
    sa.Column('dosen_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.Enum('offline', 'online', name='sesimode'), nullable=False),
    sa.Column('kode_sesi', sa.String(length=6), nullable=True),
    sa.Column('kode_expire_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pertemuan_ke', sa.Integer(), nullable=False),
    sa.Column('waktu_buka', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('waktu_tutup', sa.DateTime(timezone=True), nullable=True),
    sa.Column('batas_terlambat', sa.Interval(), nullable=True),
    sa.Column('status', sa.Enum('aktif', 'selesai', name='sesistatus'), nullable=True),
    sa.ForeignKeyConstraint(['dosen_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['matakuliah_id'], ['matakuliah.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kode_sesi')
    )
    op.create_table('kode_usage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sesi_id', sa.UUID(), nullable=False),
    sa.Column('mahasiswa_id', sa.UUID(), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['mahasiswa_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sesi_id'], ['sesi_presensi.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sesi_id', 'mahasiswa_id', name='uq_kode_usage_sesi_mahasiswa')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kode_usage')
    op.drop_table('sesi_presensi')
    op.drop_table('matakuliah')
    # ### end Alembic commands ###
